### ISSUE TITLE
Is there any api for send and deleting friend request ?

### ISSUE THREAD

**Issue by hemangjoshi37a** [alxlion/bereal-flutter#2]
Is there any api for send and deleting friend request ?

**Comment by alxlion** [comment]
It's just the front end, there isn't any API

**Comment by hemangjoshi37a** [comment]
ok fine

**Comment by hemangjoshi37a** [comment]
can you post any screenshots in the `readme.md`?

**Comment by alxlion** [comment]
I will 👍
